name: scrape
version: '1.1.0'
summary: CLI utility to scrape emails from websites
description: |
  CLI utility that scrapes emails from specified website recursively and concurrently

  Sample call: `scrape -website https://lawzava.com -depth 2`

  **Parameters**
        -async
              scan website concurrently (default true)
        -depth int
              maximum depth for recursive scan (default 1)
        -log
              print logs
        -recursively
              scan website recursively (default true)
        -website string
              specify a website to scrape (default "https://v0.vc")
confinement: strict
base: core18
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: go
    go-importpath: github.com/lawzava/scrape
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
