name: scrape
version: '1.1.0'
summary: CLI utility to scrape emails from websites
description: |
  CLI utility that scrapes emails from specified website recursively and concurrently
confinement: strict
base: core18
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: go
    go-importpath: github.com/lawzava/scrape
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
