name: scrape
version: '1.1.0'
summary: CLI utility for scraping emails.
description: |
  CLI utility that scrapes emails from specified website
confinement: strict
base: core18
parts:
  scrape:
    plugin: go
    go-importpath: github.com/lawzava/scrape
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
